// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Movie
 */
export type Movie = {
    /**
     * Movieid
     */
    movieId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Year
     */
    year: string;
    /**
     * Genre
     */
    genre: Array<string>;
    /**
     * Description
     */
    description: string | null;
    /**
     * Posterurl
     */
    posterURL: string | null;
    /**
     * Letterboxdurl
     */
    letterboxdURL: string;
    /**
     * Trailerid
     */
    trailerID: string | null;
};

/**
 * Status
 */
export enum Status {
    STARTING = 'Starting',
    VALIDATING_USERNAME = 'Validating username',
    FAILED_INVALID_USERNAME = 'Failed. Invalid username',
    WAITING_FOR_SCRAPER = 'Waiting for scraper',
    SCRAPING_USER_RATINGS = 'Scraping user ratings',
    FAILED_NO_RATINGS_TO_SCRAPE_FOR_THE_USER = 'Failed. No ratings to scrape for the user',
    FAILED_ERROR_WHILE_SCRAPING = 'Failed. Error while scraping',
    PREPROCESSING_DATA = 'Preprocessing data',
    FAILED_NO_DATA_AVAILABLE_ABOUT_THE_USER_RATED_MOVIES = 'Failed. No data available about the user-rated movies',
    FINDING_RECOMMENDATIONS = 'Finding recommendations',
    FAILED_NO_MOVIES_NOT_ALREADY_RATED_ARE_AVAILABLE_FOR_RECOMMENDATION = 'Failed. No movies not already rated are available for recommendation',
    SCRAPING_YOU_TUBE_TRAILER_IDS = 'Scraping YouTube trailer ids',
    FINISHED = 'Finished'
}

/**
 * UsernameRequest
 */
export type UsernameRequest = {
    /**
     * Username
     */
    username: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type InitSystemUsernamesPostData = {
    body: UsernameRequest;
    path?: never;
    query?: never;
    url: '/usernames/';
};

export type InitSystemUsernamesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InitSystemUsernamesPostError = InitSystemUsernamesPostErrors[keyof InitSystemUsernamesPostErrors];

export type InitSystemUsernamesPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type CheckStatusStatusGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Username
         */
        username: string;
    };
    url: '/status/';
};

export type CheckStatusStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckStatusStatusGetError = CheckStatusStatusGetErrors[keyof CheckStatusStatusGetErrors];

export type CheckStatusStatusGetResponses = {
    /**
     * Successful Response
     */
    200: Status;
};

export type CheckStatusStatusGetResponse = CheckStatusStatusGetResponses[keyof CheckStatusStatusGetResponses];

export type GetRecommendationMoviesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Username
         */
        username: string;
    };
    url: '/movies/';
};

export type GetRecommendationMoviesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecommendationMoviesGetError = GetRecommendationMoviesGetErrors[keyof GetRecommendationMoviesGetErrors];

export type GetRecommendationMoviesGetResponses = {
    /**
     * Response Get Recommendation Movies  Get
     *
     * Successful Response
     */
    200: Array<Movie>;
};

export type GetRecommendationMoviesGetResponse = GetRecommendationMoviesGetResponses[keyof GetRecommendationMoviesGetResponses];

export type GetPfpUrlPfpUrlsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Username
         */
        username: string;
    };
    url: '/pfp-urls/';
};

export type GetPfpUrlPfpUrlsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPfpUrlPfpUrlsGetError = GetPfpUrlPfpUrlsGetErrors[keyof GetPfpUrlPfpUrlsGetErrors];

export type GetPfpUrlPfpUrlsGetResponses = {
    /**
     * Response Get Pfp Url Pfp Urls  Get
     *
     * Successful Response
     */
    200: string;
};

export type GetPfpUrlPfpUrlsGetResponse = GetPfpUrlPfpUrlsGetResponses[keyof GetPfpUrlPfpUrlsGetResponses];
